### PR TITLE
successful employee_trainingPgrm table build

### PR DESCRIPTION
**Pull request by melissabell456**
## Changes

-added functionality to generate and build join table for employee_trainingPgrm
-added functionality to build table in bangazon.sqlite

## Testing

-pull down branch and run `npm run build-tables`

## Expected Result

-open db browser, you should see a new join table titled employee_trainingPgrm with below attributes

image

## Associated Ticket(s) 

#39 

## Justification

-This join table will be required when querying because employees can join multiple training programs and training programs can have multiple employees

### CODE REVIEW

**Review by dhazlettjr — CHANGES_REQUESTED** [review]
Comment on line 7, employee_trainingPgrm.js should be removed

**Review by dhazlettjr — APPROVED** [review]
Perfect

**Review by Valerie-Freeman — APPROVED** [review]
you should see a new join table titled employee_trainingPgrm with below attributes ✔️

**Review by electriceeli — APPROVED** [review]
I accept that this is acceptable

**Pull request merged**
