### PR TITLE
Vf gpp products

### PR DESCRIPTION
**Pull request by Valerie-Freeman**
## Changes
Created function to get all or one product(s)
Created function to add new product
Created function to edit product
Created function to delete product
(Not set up in controller yet, see line 45 in `products-ctrl.js`

## Testing
1. In your terminal run nodemon app.js
To get all products - migrate to localhost:8080/api/products
To get a single product - migrate to localhost:8080/api/products/(1-50)

2. To add a new employee - use PostMan
body should be raw, and have JSON(application/json) checked
headers JSON should be selected

At the top, POST should be selected with localhost:8080/api/products as the URL

Paste this in the body: 
`{
	"title": "Furby",
	"price": "52.95",
	"product_type_id": 4,
	"customer_id": 14,
	"description": "An awesome vintage toy. Use it to scare the hell out of anyone who doesn't know what it is."
}
`

3.  At the top, PUT should be selected with localhost:8080/api/products/51 as the URL

Paste this in the body:
`{
	"column": "title",
	"value": "Fuzzy Gremlin Bird"
}
`
## Expected Results
Getting all products should return JSON data with all products (1-50)
Getting a single product should return JSON data with one product
Posting a new product should return a new ID in postman. (51)
Updating a product should change the title from "Furby" to "Fuzzy Gremlin Bird"

## Tickets
#2

### CODE REVIEW

**Review by hunterphillips — CHANGES_REQUESTED** [review]
Hey Val, looks good. Only super small thing is in the product-type-ctrl:
"require('../models/Product-types'); "... types is still plural so its not reading the file
*edit* so theres a few like this, orders, employees, etc. Maybe this isn't merged with latest master?
Everything else looks nicee, approved after that

**Review by hunterphillips — APPROVED** [review]
👍

**Review by melissabell456 — APPROVED** [review]
POST ✔️ PUT ✔️ GET ALL ✔️ GET ONE ✔️

**Review by electriceeli — APPROVED** [review]
Test 1 - ✔️ 
Test 2 - ✔️ 
Test 3 - ✔️

**Pull request merged**
