### PR TITLE
setup basic file structure and example js files where needed for naming convention

### PR DESCRIPTION
**Pull request by electriceeli**
- created root items: package.json, gitignore, README (updated)
- created basic folder for: data (JSON), databases, and generators (Faker)
- installed Faker (dev dependency) and Sqlite3

### CODE REVIEW

**Review by hunterphillips — COMMENTED** [review]
DELETE

**Review by hunterphillips — CHANGES_REQUESTED** [review]
MISSING DATABASES FOLDER!!!! 👎 😞

**Review by hunterphillips — APPROVED** [review]

**Review by hunterphillips — APPROVED** [review]

**Comment by electriceeli** [comment]
Added empty JSON file so the "data" folder would actually upload :shipit:

**Review by melissabell456 — CHANGES_REQUESTED** [review]
Please update the .gitignore to include .sqlite extensions so our local dbs are not pushed up. Thank you!

**Review by dhazlettjr — APPROVED** [review]
All clear

**Comment by melissabell456** [comment]
🎖 Thanks 👍

**Pull request merged**
