### PR TITLE
Hp prod type

### PR DESCRIPTION
**Pull request by hunterphillips**
**Testing**:
- run npm install to get body-parser
- with server running on "localhost:8080/api" , add "/programs" or "/programs/1" (1 - 8) on url to see programs or single program
- with server on "localhost:8080/api/programs", use postman's POST to this url, 
select Headers-> in 'Key' field: type _Content-Type_, Value: _application/json_
in Body -> raw: add json object
```
{
   "title": "Volleyball",
   "startDate": "2019-1-1",
   "endDate": "2019-1-2",
   "max": 10
}
```
- with server on "localhost:8080/api/programs/3", use postman's PUT to this url, 
select Headers-> Key: Content-Type, Value: application/json
in Body -> raw: add json object
```
{
  "column": "start_date",
  "value": "2018-4-22"
}
```

**Changes**: 
Adds bodyParser to app.js, training programs routes, GET PUT POST route methods, training-programs-ctrl.js, Training-programs Model.js

**Expected Results** :
user should be able to: get programs and get a program via url request 
post new program and edit a program via Postman POST and PUT

Relates to #9 
PR provides basic template of full api query functionality for a specific data table

### CODE REVIEW

**Review by electriceeli — COMMENTED** [review]
Try passing in a whole object to the editProgram function to see if it will accept changing only the properties passed in by Postman.

Use req params to grab the ID from the developer

**Review by electriceeli — APPROVED** [review]
I'll admit this is at least passable

**Review by Valerie-Freeman — APPROVED** [review]
SICK, maybe add some comments? This way can can follow your code and understand what you did better when trying to write this functionality ourselves

**Review by melissabell456 — APPROVED** [review]
**Testing**:
- run npm install to get body-parser
- with server running on "localhost:8080/api" , add "/programs" or "/programs/1" (1 - 8) on url to see programs or single program ✅ 
- with server on "localhost:8080/api/programs", use postman's POST to this url, 
select Headers-> in 'Key' field: type _Content-Type_, Value: _application/json_
in Body -> raw: add json object ✅ 
```
{
   "title": "Volleyball",
   "startDate": "2019-1-1",
   "endDate": "2019-1-2",
   "max": 10
}
```
- with server on "localhost:8080/api/programs/3", use postman's PUT to this url, ✅ 
select Headers-> Key: Content-Type, Value: application/json
in Body -> raw: add json object
```
{
  "column": "start_date"
  "value": "2018-4-22"
}
```

**Changes**: 
Adds bodyParser to app.js, training programs routes, GET PUT POST route methods, training-programs-ctrl.js, Training-programs Model.js

**Expected** results:
user should be able to: get programs and get a program via url request 
post new program and edit a program via Postman POST and PUT

Relates to #9 
PR provides basic template of full api query functionality for a specific data table

**Pull request merged**
