### PR TITLE
finished table build and faker data for payment types

### PR DESCRIPTION
**Pull request by electriceeli**
Added table build and faker data 

To test run ```node build-db.js```

Associated tickets: #34, #35 

One step closer to the finishing the sqlize DB

### CODE REVIEW

**Comment by melissabell456** [comment]
To test run node build-db.js - test successful 🏅 

Associated tickets: #34, #35 - confirmed!

One step closer to the finishing the sqlize DB - PR approved

**Review by melissabell456 — APPROVED** [review]
approved - see comment above for detail

**Review by dhazlettjr — APPROVED** [review]
All Clear

**Review by hunterphillips — APPROVED** [review]

**Review by Valerie-Freeman — APPROVED** [review]
Data looks good 👍

**Pull request merged**
